export type BookedUser = {
  id: string;
  userName: string;
  firstName: string;
  lastName: string;
  emailAddress: string;
  phone: string;
  wk_ph: string;
  lastLogin: string;
  statusId: string;
  Timezone: string;
  organization: string;
  artform: string;
  organisationType: string;
  organisationName: string;
  email: string;
  address: string;
  suburb: string;
  state: string;
  country: string;
  postcode: string;
  insurance: boolean;
  organisationAbn: string;
  accountType: string;
  accurate: boolean;
  website: string;
  promo: string;
};
